version: '3'
services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    hostname: nginx
    network_mode: bridge
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - data:/etc/letsencrypt
volumes:
  data:

# https://github.com/NginxProxyManager/nginx-proxy-manager  